### PR TITLE
Allow file_type to be specified in metadata file

### PR DESCRIPTION
**Pull request by mdelillo**

### CODE REVIEW

**Comment by robdimsdale** [comment]
@mdelillo @ekcasey thanks for submitting this. Looks great. Now that we shift the default `FileType` of `Software` from `pivnet_client` to `out_command` should we also add a test in `out_command_test` around this default case in addition to the one you already added for the non-default case?

**Comment by robdimsdale** [comment]
Also @zachgersh is currently refactoring this section of the codebase so he may have some thoughts on this PR too

**Comment by zachgersh** [comment]
I am ok with this change. I may just take this and apply it to my refactor-branch. A lot of what is happening in out command is being moved around. @mdelillo how quickly would you like to see this shipped?

Also, would love to know what you are using instead of "Software"

**Comment by mdelillo** [comment]
@zachgersh Take your time, our pipeline is using a forked version of the resource we have hosted on dockerhub (hooray concourse!). It would be nice to use the real resource but we're in no rush.

We upload two files per release, one of which is an Open Source License. Setting the file type allows users to download it without being signed in.

**Comment by robdimsdale** [comment]
@mdelillo thanks for the clarification. It's helpful to understand what the different use-cases are.

Just an update on this - we're refactoring a bunch of stuff which should be finished up in the next week or so, and at that point your PR probably will need to be rebase and re-submitted, or we can just implement the work if you'd rather.

Either way, we'll leave this issue open until the refactor is complete so we can continue the conversation at that time.

**Comment by zachgersh** [comment]
Hey @mdelillo again - sorry for the delay in adding this officially but now we've got in there! You can use it if you want to be on an RC of the resource or wait for the next official release.

RC you want from dockerhub is tag `v0.18.1-rc.14`

**Pull request closed without merging**
